-- AlterTable
ALTER TABLE `ecommerce_products` MODIFY `name` VARCHAR(191) NULL,
    MODIFY `price` DOUBLE NULL,
    MODIFY `category` VARCHAR(191) NULL,
    MODIFY `user_id` INTEGER NULL,
    MODIFY `username` VARCHAR(191) NULL,
    MODIFY `email` VARCHAR(191) NULL,
    MODIFY `password` VARCHAR(191) NULL,
    MODIFY `first_name` VARCHAR(191) NULL,
    MODIFY `last_name` VARCHAR(191) NULL,
    MODIFY `order_date` DATETIME(3) NULL,
    MODIFY `status` VARCHAR(191) NULL,
    MODIFY `total_amount` DOUBLE NULL,
    MODIFY `quantity` INTEGER NULL,
    MODIFY `subtotal` DOUBLE NULL,
    MODIFY `street_address` VARCHAR(191) NULL,
    MODIFY `city` VARCHAR(191) NULL,
    MODIFY `state` VARCHAR(191) NULL,
    MODIFY `postal_code` VARCHAR(191) NULL,
    MODIFY `country` VARCHAR(191) NULL,
    MODIFY `rating` INTEGER NULL;
